### ISSUE TITLE
Question: does RandomEvent#m_nearBaseOnly = false ever work in randomevent system? 

### ISSUE THREAD

**Issue by nanonull** [ASharpPen/Valheim.CustomRaids#13]
Hey,

Question is mostly about base game system - it seams base game doesn't run random events when player is not in his base even if RandomEvent#m_nearBaseOnly = false. Is there a way to run randomevents out of player base?

For example:
0 Create Raid config with NearBaseOnly = false property
1 Player runs 20+ meters out of his base (but don't enter any other biom)
2 Open console and enter: imacheater
3 Enter to console: randomevent

Actual result:
game log says: Possible events:0
And any event doesn't start

I enter to console 'event <Event_Name>' to double-check that Raid config is at least valid - event is started after this command

4 Player enters his Base
5 Enter to console: randomevent

Actual=Expected:
Possible events:1+
And event will start on schedule.

The line where RandomEvent#m_nearBaseOnly is set:
https://github.com/ASharpPen/Valheim.CustomRaids/blob/f8d09fe86469fd4e21f7a5ddaf1d7b4dd9719e25/Valheim.CustomRaids/Patches/RaidEventSystemPatch.cs#L184

Raid config:
Random = true
NearBaseOnly = false

[custom_raids.supplemental.dwarfs.cfg.txt](https://github.com/ASharpPen/Valheim.CustomRaids/files/6131665/custom_raids.supplemental.dwarfs.cfg.txt)

**Comment by ASharpPen** [comment]
The game seem to have a bug with that. The NearBaseOnly property seem to be required true for now, for the random events to properly run.

I don't quite remember off the top of my head, but the base check may just be for the checks the game does when starting the event, and not for the actual spawning.
You can find some of the explanation behind this in the valheim wiki:
https://github.com/Valheim-Modding/Wiki/wiki/Valheim-Event-System
https://github.com/Valheim-Modding/Wiki/wiki/Spawning
