### ISSUE TITLE
Potential issue with RandomEvent

### ISSUE THREAD

**Issue by FractusNine** [ASharpPen/Valheim.CustomRaids#56]
Hi ASharpPen,

I'm not entirely sure what is happening, but it looks like events have not been triggering over the last week or two on our dedicated server.  I just tested with all mods disabled, and on a local world, but seem to be getting the same issue.  The events worked fine in the past too, so I'm thinking it may not be due to a config error.  I've also updated to BepInEx 5.4.10.0, which might matter?

This is what I've tested:
Uninstalled all mods, went near a settlement, and confirmed that "randomevent" console command triggers a vanilla raid
Installed only CustomRaids, went to same spot, and "randomevent" no longer triggers a raid, not even vanilla raids.
Triggering a custom raid manually using "event X" works fine though, and runs as expected.  

I see this in the debug log:
[Debug  :Custom Raids] Checking 0 raids for conditionals
[Info   : Unity Log] 05/13/2021 17:18:45: Possible events:0

Hope that gives you enough information to troubleshoot -- let me know if you need any further information!

Quick Edit: I meant I am using BepInEx 5.4.10.01 released 12 May

**Comment by ASharpPen** [comment]
Confirmed this during testing of the next version today. 
Identified issue. Current workaround is to use Individual Raid Frequency overhaul.

Fix will be included in next version.

**Comment by FractusNine** [comment]
That makes sense -- now that you mention it, I did turn individual frequencies off a little while ago.  Thanks for working on the issue!
