### ISSUE TITLE
Mistlands update?

### ISSUE THREAD

**Issue by pjmichor** [ASharpPen/Valheim.CustomRaids#87]
Hello!

Do you plan to update the various mods to be compatible with Mistlands and its new raids/enemies?

Thank you!

**Comment by ASharpPen** [comment]
Yes. I expect to release new versions of Custom Raids and Spawn That later today.

Both have pre-releases available until then, that were built for the public test branch:
- https://github.com/ASharpPen/Valheim.CustomRaids/releases
- https://github.com/ASharpPen/Valheim.SpawnThat/releases

**Comment by pjmichor** [comment]
Awesome, looking forward to it.
